### ISSUE TITLE
Resurrect buildbot with a new strength

### ISSUE THREAD

**Issue by yarikoptic** [datalad/buildbot#5]
I hope to find some time in the nearest future to get back to our build bot and establish regression testing runs for datalad and git-annex under various scenarios (OS/file systems).  Plan to do a matrix for

- project (so will build/test from master)
  - [ ] git-annex
  - [ ] datalad - I guess ideally should be tested against released and devel versions of git-annex
  - [ ] datalad-containers
  - [ ] datalad-neuroimaging
  - [ ] datalad-metalad
- OS
  - Debian
     - [ ] stable
     - [ ] unstable
  - Windows (probably via virtualbox)
    - [ ] 11
    - [ ] WSL
  - OSX
    - [ ] some box with a recentish, native
    - may be will add a run under Docker.  We might like to assure correct operations in docker envs, since we did see some glitches
- file systems (many would be tested only under a single Debian env)
  - native
  - [ ] NFS (possibly with some different settings, e.g. sync vs nosync)
  - [ ] crippled (vFAT)
  - ideally also
    - [ ] lustre (I didn't realize that it itself is FOSS, although not in mainline/debian, https://wiki.debian.org/Lustre). Used at many HPC deployments
    - [ ] ZFS

It would be cool also if we could add benchmarking to the matrix runs to see differences between setups, even if they would often be more suggestive than proper comparisons.

I will probably not reincarnate CI of the pull requests, although might eventually be done.

Most likely will just do it primarily on smaug for the main buildbot server and workers (besides OSX)

Goals:
- move some runs away from travis to lighten it up
- discovery of corner cases which we do not address and do not know yet about. 
- early alert on regressions in git-annex and datalad to avoid such issues as https://github.com/datalad/datalad/issues/3675 etc.

Notes/Questions

### Q1: Windows

@mih - do you have some notes on how to configure/use a Windows (virtual) box and possibly WSL (#4) ?
  
I guess at large it would be miniconda installation pulling all dependencies for datalad, and then replacing it with the version to check.  But then all the additional gotchas (like discovered shell config for the openssh) would be of value as well.

### Q2: additional setups

Any other file systems tools to be checked independently?

### Q3: OSX

I guess the elderly Apple box  I have might  is way too old.  Need to find a more suitable replacement

**Comment by mih** [comment]
re Windows: WSL2 in a VM only works on AMD cpus so far (nested virtualization). All installation docs/reports are here:

- https://github.com/datalad-handbook/book/issues/132
- https://github.com/datalad-handbook/book/issues/110
- https://github.com/datalad-handbook/book/issues/114

It would be useful to have this system be open to additional workers. I can see a clear interest in people/projects providing their own workers to be able to test very specifically their particular setups.

**Comment by bpoldrack** [comment]
Re project:
Maybe include datalad-metalad? Should become quite important in the foreseeable future.

**Comment by bpoldrack** [comment]
> I will probably not reincarnate CI of the pull requests, although might eventually be done.

At least a Win and a OSX run would be nice, though.

**Comment by bpoldrack** [comment]
Re Q2:

Maybe some gvfs-sftp mounted thing? I vaguely remember  having run into trouble with that at some point.

**Comment by yarikoptic** [comment]
> people/projects providing their own workers to be able to test very specifically their particular setups

they already can via `git annex test; datalad test` AFAIK.  Or do you mean them being able to register their buildbot clients to report back to our system?

**Comment by yarikoptic** [comment]
> Maybe include datalad-metalad? Should become quite important in the foreseeable future.

good point ;) added!  although it might (or might not) eventually migrate into the core since `metadata` is within the 2nd tear of the core:
![API](https://raw.githubusercontent.com/datalad/talk-2019-mila/master/pics/API-interdependencies.png)

**Comment by mih** [comment]
> they already can via `git annex test; datalad test` AFAIK. Or do you mean them being able to register their buildbot clients to report back to our system?

Yes, I meant the latter. Sure thing anyone can run tests, but it would be instrumental for **us** to know if we break or slow down real 3rd-party deployments. If a project like OpenNeuro could setup a test env that verifies and reports what is going on in master, we could move forward with much more confidence.

re metalad: The plan is to replace metadata handling in -core ASAP with the extension code.

**Comment by mih** [comment]
Here is something to keep in mind: https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

Future features include self-hosted runners.

**Comment by yarikoptic** [comment]
I don't mind placing all eggs into the github CI basket ;)  we will see how easy it would be to setup.
